version: '2'
services:
  mgc:
    image: msgraph-cli
    cap_add:
    # https://man7.org/linux/man-pages/man7/capabilities.7.html
    # 
    - IPC_LOCK # Required by gnome-keyring daemon, the dbus secret service
    environment:
      - KEYRING_PASSWORD=changeit
    volumes:
      - ./tmp/.mgc:/root/.mgc
      - ./tmp/.IdentityService:/root/.local/share/.IdentityService
      - ./tmp/keyrings:/root/.local/share/keyrings